name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 4,10,16,22 * * *" #北京时间 12,18,0,6 点
  workflow_dispatch:     # 支持手动触发

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }} # 仅当是 Fork 仓库时才运行
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: kitsurato/mini-gkms-box
          upstream_sync_branch: main  # 上游要同步的分支名
          target_sync_branch: main    # 你 Fork 的目标分支名
          test_mode: false
